### PR TITLE
Compare jekyll build output in CI

### PR DESCRIPTION
**Pull request by TooManyBees**
closes https://github.com/github/pages-engineering/issues/893

Instead of uploading build artifacts, the test actions compare generated output to expected output. Raises an error when an expected file is missing, an unexpected file is created, or when an actual file doesn't match an expected file.

Also adds 2 new test projects to verify that the `future` config option works as expected.

There is a new script `bin/record-expected-output` which uses the [`act`](https://github.com/nektos/act) utility to run the jekyll build action through docker, so expected output will be consistent with what the real action builds.

### CODE REVIEW

**Comment by TooManyBees** [comment]
Biggest puzzle I am unable to solve is this:
```diff
19c19
< {"@type":"WebSite","headline":"Jekyll Actions Demo","name":"Jekyll Actions Demo","url":"[https://github.com/pages/actions/jekyll-build-pages/](https://github.com/pages/actions/jekyll-build-pages/)","@context":"[https://schema.org](https://schema.org/)"}</script>
---
> {"url":"[https://github.com/pages/actions/jekyll-build-pages/](https://github.com/pages/actions/jekyll-build-pages/)","@type":"WebSite","headline":"Jekyll Actions Demo","name":"Jekyll Actions Demo","@context":"[https://schema.org](https://schema.org/)"}</script>
```

jsonifying the seo values emits the keys in different order when run locally (whether that's in a docker container or not) than on the real actions runner. This is confusing because we're using the same version of Ruby (2.7.4) and jekyll-seo-tag (2.7.1).

In a pinch I'll find a way to ignore these lines when comparing diffs, but I would not like to resort to that.

**Comment by parkr** [comment]
@TooManyBees hi! We're actually working on that very problem: https://github.com/jekyll/jekyll-seo-tag/pull/458. Just needs mattr-'s approval :)

**Comment by TooManyBees** [comment]
> @TooManyBees hi! We're actually working on that very problem: [jekyll/jekyll-seo-tag#458](https://github.com/jekyll/jekyll-seo-tag/pull/458). Just needs mattr-'s approval :)

I would love to know *why* this inconsistency manifests, since as far as I know hash keys preserve their insertion order for since, um, Ruby 1.9.0. Does it have anything to do with the logic that determines which of the drop's instance methods count as hash keys?

**Comment by parkr** [comment]
> I would love to know _why_ this inconsistency manifests, since as far as I know hash keys preserve their insertion order for since, um, Ruby 1.9.0. Does it have anything to do with the logic that determines which of the drop's instance methods count as hash keys?

I tried to see if it was the `jsonify()` filter and I couldn't reproduce differing key order in the code, so I'm not sure what's up. For now, sorting the keys when building the Hash to jsonify works for this particular use-case.

**Comment by TooManyBees** [comment]
One thing that's curious is that key order seems to be consistent on the same platform (as in, the jekyll-build-pages image)

**Review by YiMysty — APPROVED** [review]

**Comment by parkr** [comment]
Hey @TooManyBees! We shipped that fix and @hubot's PR is helpfully opened for your consideration: https://github.com/github/pages-gem/pull/817

**Pull request merged**
